# Dedo Nervoso specific rules. The game uses no reflection or serialization by class name, so the
# default Android rules plus the manifest-derived keeps generated by aapt2 are sufficient.
-keep class com.dedonervoso.app.MainActivity { *; }
